---
title: "cTWAS network analysis"
output: html_document
date: '2025-9-7'
editor_options: 
  chunk_output_type: console
---


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(igraph)
library(ggraph)
library(tidygraph)
library(tidyverse)
```

```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.width= 12, fig.height= 12}
string <- read.table("/project/xinhe/shengqian/cTWAS_paper_figures/data/string_LDL.tsv",header = F)
graph <- graph_from_data_frame(d = string, directed = FALSE)
comp <- components(graph)
V(graph)$component <- comp$membership
set.seed(123)
ggraph(graph, layout = "fr", niter = 1000, area = vcount(graph)^2.4) +
  geom_edge_link(aes(alpha = 0.4), color = "grey70") +
  geom_node_point(aes(color = factor(component)), size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void() + theme(legend.position = "none")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.width= 12, fig.height= 12}
string <- read.table("/project/xinhe/shengqian/cTWAS_paper_figures/data/string_IBD.tsv",header = F)
graph <- graph_from_data_frame(d = string, directed = FALSE)
comp <- components(graph)
V(graph)$component <- comp$membership
set.seed(1233)
ggraph(graph, layout = "fr", niter = 1000, area = vcount(graph)^2.4) +
  geom_edge_link(aes(alpha = 0.4), color = "grey70") +
  geom_node_point(aes(color = factor(component)), size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void() + theme(legend.position = "none")
```