---
title: "LDL - Liver and Adipose - E and S"
output: html_document
date: '2023-12-30'
---

### Load ctwas results

```{r}
outputdir <- "/project/xinhe/shengqian/cTWAS_analysis/data/test_context/"
outname <- "test_context_ctwas"
gwas_n <- 343621
thin <- 0.1

ctwas_parameters <- ctwas:::ctwas_summarize_parameters(outputdir = outputdir, 
                                               outname = outname, 
                                               gwas_n = 343621, 
                                               thin = 0.1,
                                               plot_estimates = T)
```


```{r}
ctwas_parameters$group_size
ctwas_parameters$group_prior
ctwas_parameters$group_prior_var
ctwas_parameters$enrichment
ctwas_parameters$group_pve
```

```{r,out.width="50%"}
#pdf(file = "./primary_set2.pdf", width = 5, height = 5)
ctwas_parameters$convergence_plot
```

```{r}
results <- data.table::fread("/project/xinhe/shengqian/cTWAS_analysis/data/test_context/test_context_ctwas.susieIrss.txt")
gene_res <- results[results$type!='SNP',]
gene_res <- gene_res[order(-gene_res$susie_pip),]
head(gene_res)
```

