---
title: "Comparing enriched terms found by fractional model/enrichR for multigroup&singlegroup"
author: "XSun"
date: "2025-05-27"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true

---

# Introduction

We did enrichment analysis using fractional model and enrichR. The GO data set we used is GO_Biological_Process_2023


```{r}
library(ggplot2)

traits <- c("LDL-ukb-d-30780_irnt","aFib-ebi-a-GCST006414", "IBD-ebi-a-GCST004131", "SBP-ukb-a-360", "T1D-GCST90014023"#, "Height-panukb", "HTN-panukb", "PLT-panukb", "RA-panukb", "RBC-panukb", "ATH_gtexukb"
            )
# "BMI-panukb", "HB-panukb", "WBC-ieu-b-30", "T2D-panukb", "SCZ-ieu-b-5102", "BIP-ieu-b-5110", "ASD-ieu-a-1185", "ADHD-ieu-a-1183", "PD-ieu-b-7", "NS-ukb-a-230", "MDD-ieu-b-102"

folder_fractional_multi <- "/project/xinhe/xsun/multi_group_ctwas/23.multi_group_0515/results_downstream/enrich_fractional_multi_allgenes//"
folder_fractional_single <- "/project/xinhe/xsun/multi_group_ctwas/23.multi_group_0515/results_downstream/enrich_fractional_single_allgenes//"
folder_enrichr_multi <- "/project/xinhe/xsun/multi_group_ctwas/23.multi_group_0515/results_downstream/enrich_enrichr_multi/"
folder_enrichr_single <- "/project/xinhe/xsun/multi_group_ctwas/23.multi_group_0515/results_downstream/enrich_enrichr_single/"

```



```{r fig.height=5,fig.width=5}

for (trait in traits){
  
  df_frac_multi <- readRDS(paste0(folder_fractional_multi,"enrichment_fractional_calibrated_blgeneset_summary_multigroup_",trait,"_GO_Biological_Process_2023.RDS"))
  
  df_fdr005_multi <- df_frac_multi[df_frac_multi$fdr_combined < 0.05,]
  df_fdr005_multi <- df_fdr005_multi[complete.cases(df_fdr005_multi$fdr_combined),]
  num_frac_multi <- nrow(df_fdr005_multi)
  
  df_frac_single <- readRDS(paste0(folder_fractional_single,"enrichment_fractional_calibrated_blgeneset_summary_singlegroup_",trait,"_GO_Biological_Process_2023.RDS"))
  
  df_fdr005_single <- df_frac_single[df_frac_single$fdr_combined < 0.05,]
  df_fdr005_single <- df_fdr005_single[complete.cases(df_fdr005_single$fdr_combined),]
  num_frac_single <- nrow(df_fdr005_single)
  
  file_enrichr_multi <- paste0(folder_enrichr_multi,trait,".enrichr_GO_Biological_Process_2023.RDS")
  if(file.exists(file_enrichr_multi)) {
    df_enrichr_multi <- readRDS(file_enrichr_multi)
    df_enrichr_multi <- df_enrichr_multi[df_enrichr_multi$Adjusted.P.value < 0.05,]
    num_enrichr_multi <- nrow(df_enrichr_multi)
  }else{
    num_enrichr_multi <- 0
  }
  
  file_enrichr_single <- paste0(folder_enrichr_single,trait,".enrichr_GO_Biological_Process_2023.RDS")
  if(file.exists(file_enrichr_single)) {
    df_enrichr_single <- readRDS(file_enrichr_single)
    df_enrichr_single <- df_enrichr_single[df_enrichr_single$Adjusted.P.value < 0.05,]
    num_enrichr_single <- nrow(df_enrichr_single)
  }else{
    num_enrichr_single <- 0
  }
  
  df <- data.frame(
    Category = factor(
      c("Fractional \nMulti-group", "Fractional \nSingle-group", "Enrichr \nMulti-group", "Enrichr \nSingle-group"),
      levels = c("Fractional \nMulti-group", "Fractional \nSingle-group", "Enrichr \nMulti-group", "Enrichr \nSingle-group")
    ),
    Value = c(num_frac_multi, num_frac_single, num_enrichr_multi, num_enrichr_single)
  )
  
  # Generate the bar plot
  p <- ggplot(df, aes(x = Category, y = Value)) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = Value), vjust = -0.5, size = 5) +
    labs(title = trait, x = "", y = "Count") +
    theme_minimal(base_size = 14) +
    theme(axis.text.x = element_text(angle = 20, hjust = 1))
  
  print(p)
}



```
