---
title: "Region Merge Test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup dir}
library(ctwas)
library(data.table)
source("/project/xinhe/shengqian/cTWAS_simulation/summarize_basic_plots.R")
source("/project/xinhe/shengqian/cTWAS_simulation/summarize_ctwas_plots.R")

#outputdir1 = "/project/xinhe/shengqian/cTWAS_simulation/simulation_ctwas_rss_20210416/"
#outputdir2 = "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_oldmergeon/"
#outputdir3 = "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_mergeoff/"
outputdir = "/project2/mstephens/causalTWAS/simulations/simulation_ctwas_rss_20210416/"
runtag = "ukb-s80.45-adi"
#runtag2 = "ukb-s80.45-3"
#runtag3 = "ukb-s80.45-3"
configtag = 1
```

## PIP calibration
### PIP plot under different settings.
UKBB individual genotype data. PredictedDB Liver weights. UKBB LD matrix. Gene PVE = 0.05 and SNP PVE = 0.3. 


```{r pipplotfunc, echo=F}
plot_PIP <- function(outputdir, configtag, runtag,  simutags, ...){
   phenofs <- paste0(outputdir, runtag, "_simu", simutags, "-pheno.Rd")
   susieIfs <- paste0(outputdir, runtag, "_simu",simutags, "_config", configtag,".susieIrss.txt")

   f1 <- caliPIP_plot(phenofs, susieIfs, ...) 
   return(f1)
}
```

```{r pipplot, fig.width= 12, fig.height= 4, echo=F}
#simutaglist = list(paste(4, 1:5, sep = "-"), paste(1, 1:5, sep="-"), paste(1, 1:5, sep="-"))
#f1 <- plot_PIP(outputdir1, configtag, runtag1, simutaglist[[1]], main = "old merge off")
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
#simutaglist = paste(1, 1:5, sep = "-")
#f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
#f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```


```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(2, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(3, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(4, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(5, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(6, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(7, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(8, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```

```{r fig.width= 12, fig.height= 4, echo=F}
simutaglist = paste(9, 1:5, sep = "-")
f <- plot_PIP(outputdir, configtag, runtag, simutaglist, main = "old merge off")
f
#f2 <-  plot_PIP(outputdir2, configtag, runtag2, simutaglist[[2]], main = "merge on")
#f3 <-  plot_PIP(outputdir3, configtag, runtag3, simutaglist[[3]], main = "new merge off")
#gridExtra::grid.arrange(f1, f2, f3, ncol =3)
```