---
title: "Seven Correlated Tissues Simulation"
author: "shengqian"
date: "2023-12-30"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(ctwas)
library(data.table)
source("/project/xinhe/shengqian/cTWAS_simulation/code/simulation_help_functions.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_basic_plots.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_ctwas_plots.R")
#source("/project2/xinhe/shengqian/cTWAS/cTWAS_analysis/analysis/simulation_help_functions.R")

plot_PIP_estimatedL <- function(results_dir, runtag,  simutags, LD_type, ...){
   phenofs <- paste0(results_dir, runtag, "_simu", simutags, "-pheno.Rd")
   susieIfs <- paste0(results_dir, runtag, "_simu",simutags, "_", LD_type, ".estimatedL.finemap_regions_res.RDS")
   f1 <- caliPIP_plot_csindex(phenofs, susieIfs, ...) 
   return(f1)
}

plot_PIP_nonSNPpip <- function(results_dir, runtag,  simutags, LD_type, ...){
   phenofs <- paste0(results_dir, runtag, "_simu", simutags, "-pheno.Rd")
   susieIfs <- paste0(results_dir, runtag, "_simu",simutags, "_", LD_type, ".nonSNPpip.finemap_regions_res.RDS")
   f1 <- caliPIP_plot_csindex(phenofs, susieIfs, ...) 
   return(f1)
}

plot_gene_PIP_estimatedL <- function(configtag, runtag,  simutags, LD_type, ...){
   phenofs <- paste0(results_dir, runtag, "_simu", simutags, "-pheno.Rd")
   susieIfs <- paste0(results_dir, runtag, "_simu",simutags, "_", LD_type, ".estimatedL.finemap_regions_res.RDS")
   f1 <- caliPIP_plot_multi_tissues(phenofs, susieIfs, ...) 
   return(f1)
}

plot_gene_PIP_nonSNPpip <- function(configtag, runtag,  simutags, LD_type, ...){
   phenofs <- paste0(results_dir, runtag, "_simu", simutags, "-pheno.Rd")
   susieIfs <- paste0(results_dir, runtag, "_simu",simutags, "_", LD_type, ".nonSNPpip.finemap_regions_res.RDS")
   f1 <- caliPIP_plot_multi_tissues(phenofs, susieIfs, ...) 
   return(f1)
}
```

## Simulation 1: Expression trait in liver with 3% PVE and 0.9% Prior


```{r, message=FALSE, warning=FALSE, echo=FALSE}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_seven_correlated_tissues_expression/"
runtag = "7corr"
simutags <- paste(1, 1:5, sep = "-")
for(simutag in simutags){
    regions <- readRDS(paste0(results_dir,runtag,"_simu",simutag,"_","UKBBLD",".estimatedL.screened_region_data.RDS"))
    print(length(regions))
}
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_seven_correlated_tissues_expression/"
runtag = "7corr"
simutags <- paste(1, 1:5, sep = "-")
for(simutag in simutags){
    regions <- readRDS(paste0(results_dir,runtag,"_simu",simutag,"_","UKBBLD",".nonSNPpip.screened_region_data.RDS"))
    print(length(regions))
}
```


```{r}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_seven_uncorrelated_tissues_expression/"
runtag = "7uncorr"
simutags <- paste(1, 1:5, sep = "-")
param_UKBB_df <- load_parameters(results_dir, runtag, simutags, "UKBBLD")
```

### Estimated Prior Inclusion Probability and PVE (UKBB LD)
`````{r, fig.width= 12, fig.height= 4, message=FALSE, warning=FALSE, echo=FALSE}
par(mfrow = c(1, 3))
y1 <- param_UKBB_df$`prior_Artery_Aorta|expression`
y2 <- param_UKBB_df$`prior_Spleen|expression`
y3 <- param_UKBB_df$`prior_Skin_Not_Sun_Exposed_Suprapubic|expression`
y4 <- param_UKBB_df$`prior_Lung|expression`
y5 <- param_UKBB_df$`prior_Adipose_Subcutaneous|expression`
y6 <- param_UKBB_df$`prior_Pancreas|expression`
y7 <- param_UKBB_df$`prior_Heart_Atrial_Appendage|expression`
truth <- rbind(c(1,0.009),c(2,0.009),c(3,0.009),c(4,0),c(5,0),c(6,0),c(7,0))
est <- rbind(cbind(1,y1),cbind(2,y2),cbind(3,y3),cbind(4,y4),cbind(5,y5),cbind(6,y6),cbind(7,y7))
plot_par_7(truth,est,xlabels = c("Artery","Spleen","Skin","Lung","Adipose","Pancreas","Heart"),ylim=c(0,0.025),ylab="Prior inclusion")

y1 <- param_UKBB_df$`pve_Artery_Aorta|expression`
y2 <- param_UKBB_df$`pve_Spleen|expression`
y3 <- param_UKBB_df$`pve_Skin_Not_Sun_Exposed_Suprapubic|expression`
y4 <- param_UKBB_df$`pve_Lung|expression`
y5 <- param_UKBB_df$`pve_Adipose_Subcutaneous|expression`
y6 <- param_UKBB_df$`pve_Pancreas|expression`
y7 <- param_UKBB_df$`pve_Heart_Atrial_Appendage|expression`

truth <- rbind(c(1,0.03),c(2,0.03),c(3,0.03),c(4,0),c(5,0),c(6,0),c(7,0))
est <- rbind(cbind(1,y1),cbind(2,y2),cbind(3,y3),cbind(4,y4),cbind(5,y5),cbind(6,y6),cbind(7,y7))
plot_par_7(truth,est,xlabels = c("Artery","Spleen","Skin","Lung","Adipose","Pancreas","Heart"),ylim=c(0,0.06),ylab="PVE")

y1 <- param_UKBB_df$`enrichment_Artery_Aorta|expression`
y2 <- param_UKBB_df$`enrichment_Spleen|expression`
y3 <- param_UKBB_df$`enrichment_Skin_Not_Sun_Exposed_Suprapubic|expression`
y4 <- param_UKBB_df$`enrichment_Lung|expression`
y5 <- param_UKBB_df$`enrichment_Adipose_Subcutaneous|expression`
y6 <- param_UKBB_df$`enrichment_Pancreas|expression`
y7 <- param_UKBB_df$`enrichment_Heart_Atrial_Appendage|expression`
  
truth <- rbind(c(1,36),c(2,36),c(3,36),c(4,0),c(5,0),c(6,0),c(7,0))
est <- rbind(cbind(1,y1),cbind(2,y2),cbind(3,y3),cbind(4,y4),cbind(5,y5),cbind(6,y6),cbind(7,y7))
plot_par_7(truth,est,xlabels = c("Artery","Spleen","Skin","Lung","Adipose","Pancreas","Heart"),ylim=c(0,250),ylab= "Enrichment")
```


### PIP Calibration Plot of expression traits
```{r, fig.width= 12, fig.height= 4, echo=FALSE, warning=FALSE}
f1 <- plot_PIP_estimatedL(results_dir, runtag, simutags, "UKBBLD", main = "Estimated L")
f2 <- plot_PIP_nonSNPpip(results_dir, runtag, simutags, "UKBBLD", main = "nonSNPpip")
gridExtra::grid.arrange(f1, f2, ncol = 2)
```

```{r, fig.width= 12, fig.height= 4, echo=FALSE, warning=FALSE}
f1 <- plot_gene_PIP_estimatedL(results_dir, runtag, simutags, "UKBBLD", main = "Estimated L")
f2 <- plot_gene_PIP_nonSNPpip(results_dir, runtag, simutags, "UKBBLD", main = "nonSNPpip")
gridExtra::grid.arrange(f1, f2, ncol = 2)
```
