---
title: "simulation_one_tissue_no_enrichment"
output: html_document
date: '2024-3-18'
editor_options: 
  chunk_output_type: console
---

## One tissue simulation
```{r echo=FALSE}
library(ctwas)
library(tidyr)
library(dplyr)
library(ggplot2)
library(data.table)
library(ggbreak) 
library(ggpubr)
library(gridExtra)
source("/project/xinhe/shengqian/cTWAS_simulation/code/simulation_help_functions.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_basic_plots.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_ctwas_plots.R")

plot_prior_inclusion <- function(results_dir,runtag,simutags,thins,group_prior_var_structures,null_methods, file_name, true_value_gene,true_value_SNP){
  par(mfrow = c(1, 2))
  for(group_prior_var_structure in group_prior_var_structures){
    for(thin in thins){
      param_df_ctwas <- load_parameters(results_dir, runtag, simutags, thin, group_prior_var_structure, "ctwas", file_name)
      y1 <- param_df_ctwas$`prior_liver|expression`
      y2 <- param_df_ctwas$prior_SNP
      param_df_susie <- load_parameters(results_dir, runtag, simutags, thin, group_prior_var_structure, "susie", file_name)
      y3 <- param_df_susie$`prior_liver|expression`
      y4 <- param_df_susie$prior_SNP
      truth <- rbind(c(1,true_value_gene),c(2,true_value_SNP),c(3,true_value_gene),c(4,true_value_SNP))
      est <- rbind(cbind(1,y1),cbind(2,y2),cbind(3,y3),cbind(4,y4))
      plot_par_4(truth,est,xlabels = c("Gene (ctwas)", "SNP (ctwas)", "Gene (susie)","SNP (susie)"),ylim=c(0,max(est[,2],truth[,2])),ylab="Prior inclusion", main=group_prior_var_structure)
    }
  }
}

plot_prior_variance <- function(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP){
  par(mfrow = c(1, 2))
  for(group_prior_var_structure in group_prior_var_structures){
    for(thin in thins){
      param_df_ctwas <- load_parameters(results_dir, runtag, simutags, thin, group_prior_var_structure, "ctwas", file_name)
      y1 <- param_df_ctwas$`prior_var_liver|expression`
      y2 <- param_df_ctwas$prior_var_SNP
      param_df_susie <- load_parameters(results_dir, runtag, simutags, thin, group_prior_var_structure, "susie", file_name)
      y3 <- param_df_susie$`prior_var_liver|expression`
      y4 <- param_df_susie$prior_var_SNP
      truth <- rbind(c(1,true_value_gene),c(2,true_value_SNP),c(3,true_value_gene),c(4,true_value_SNP))
      est <- rbind(cbind(1,y1),cbind(2,y2),cbind(3,y3),cbind(4,y4))
      plot_par_4(truth,est,xlabels = c("Gene (ctwas)", "SNP (ctwas)", "Gene (susie)","SNP (susie)"),ylim=c(0,max(est[,2],truth[,2])),ylab="Prior variance", main=group_prior_var_structure)
    }
  }
}

plot_enrichment <- function(results_dir, runtag, thins, group_prior_var_structures, null_methods, file_name, enrichment_true) {
  plots <- list()  # Store plots in a list
  plot_idx <- 1
  
  for (group_prior_var_structure in group_prior_var_structures) {
    for (thin in thins) {
      param_df_ctwas <- load_parameters(results_dir, runtag, simutags, thin, group_prior_var_structure, "ctwas", file_name)
      param_df_susie <- load_parameters(results_dir, runtag, simutags, thin, group_prior_var_structure, "susie", file_name)

      df <- data.frame(null_method = rep(c("ctwas", "susie"), each = 10),
                       pos = c(rep(1, 10), rep(2, 10)),
                       enrichment = c(param_df_ctwas$`enrichment_liver|expression`, param_df_susie$`enrichment_liver|expression`),
                       se = c(param_df_ctwas$`enrichment_se_liver|expression`, param_df_susie$`enrichment_se_liver|expression`))  # Fix repeated `se` values
      
      df$pos <- jitter(df$pos, amount = 0.2)
      
      p <- ggplot(df, aes(x = pos, y = enrichment, group = null_method, color = null_method)) +
        geom_point() +
        geom_errorbar(aes(ymin = enrichment - 1.96 * se, ymax = enrichment + 1.96 * se), width = 0.01) +
        geom_hline(yintercept = enrichment_true, linetype = "dashed", color = "blue") +
        labs(x = "", y = "log(Enrichment)", title = paste("Enrichment -", group_prior_var_structure, "Thin =", thin)) +
        scale_x_continuous(breaks = c(1, 2), labels = c("Gene (ctwas)", "Gene (susie)")) +
        ylim(c(-5,5)) +
        theme_minimal()
      
      plots[[plot_idx]] <- p  # Store plot in the list
      plot_idx <- plot_idx + 1
    }
  }
  
  # Arrange plots side by side
  if (length(plots) > 1) {
    grid.arrange(grobs = plots, ncol = length(plots))  # Using gridExtra
    # print(plots[[1]] + plots[[2]])  # Alternative using patchwork (uncomment if using patchwork)
  } else {
    print(plots[[1]])  # Just print a single plot if there's only one
  }
}
```

## Enrichment=1
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_enrichment/"
runtag = "one_tissue"
simutags <- paste(1, 1:10, sep = "-")
thins <- c(1)
group_prior_var_structures <- c("shared_all","shared_type")
null_methods <- c("ctwas","susie")
```

```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 0
file_name <- ".Gtest.minp0.mingene0.parameters.RDS"
plot_enrichment(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene)
```

### Prior Inclusion Probability
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 0.0025
true_value_SNP <- 0.0025
plot_prior_inclusion(results_dir,runtag,simutags,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

### Prior Variance
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 10.81125
true_value_SNP <- 10.81125
plot_prior_variance(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

## Enrichment=10
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_enrichment/"
runtag = "one_tissue"
simutags <- paste(2, 1:10, sep = "-")
thins <- c(1)
group_prior_var_structures <- c("shared_all","shared_type")
null_methods <- c("ctwas","susie")
```

```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- log(10)
file_name <- ".Gtest.minp0.mingene0.parameters.RDS"
plot_enrichment(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene)
```

### Prior Inclusion Probability
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 0.025
true_value_SNP <- 0.0025
plot_prior_inclusion(results_dir,runtag,simutags,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

### Prior Variance
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 10.81125
true_value_SNP <- 10.81125
plot_prior_variance(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

## Enrichment=20
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_enrichment/"
runtag = "one_tissue"
simutags <- paste(3, 1:10, sep = "-")
thins <- c(1)
group_prior_var_structures <- c("shared_all","shared_type")
null_methods <- c("ctwas","susie")
```

```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- log(20)
file_name <- ".Gtest.minp0.mingene0.parameters.RDS"
plot_enrichment(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene)
```

### Prior Inclusion Probability
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 0.05
true_value_SNP <- 0.0025
plot_prior_inclusion(results_dir,runtag,simutags,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

### Prior Variance
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 10.81125
true_value_SNP <- 10.81125
plot_prior_variance(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

## Enrichment=40
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_enrichment/"
runtag = "one_tissue"
simutags <- paste(4, 1:10, sep = "-")
thins <- c(1)
group_prior_var_structures <- c("shared_all","shared_type")
null_methods <- c("ctwas","susie")
```

```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- log(40)
file_name <- ".Gtest.minp0.mingene0.parameters.RDS"
plot_enrichment(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene)
```

### Prior Inclusion Probability
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 0.1
true_value_SNP <- 0.0025
plot_prior_inclusion(results_dir,runtag,simutags,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

### Prior Variance
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 10.81125
true_value_SNP <- 10.81125
plot_prior_variance(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```


## Enrichment=80
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_enrichment/"
runtag = "one_tissue"
simutags <- paste(5, 1:10, sep = "-")
thins <- c(1)
group_prior_var_structures <- c("shared_all","shared_type")
null_methods <- c("ctwas","susie")
```

```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- log(80)
file_name <- ".Gtest.minp0.mingene0.parameters.RDS"
plot_enrichment(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene)
```

### Prior Inclusion Probability
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 0.2
true_value_SNP <- 0.0025
plot_prior_inclusion(results_dir,runtag,simutags,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```

### Prior Variance
```{r,echo=FALSE,fig.width= 10, fig.height= 5}
true_value_gene <- 10.81125
true_value_SNP <- 10.81125
plot_prior_variance(results_dir,runtag,thins,group_prior_var_structures,null_methods,file_name,true_value_gene,true_value_SNP)
```