---
title: "simulation_one_tissue_enrichment"
output: html_document
date: '2024-4-28'
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(ctwas)
library(tidyr)
library(dplyr)
library(ggplot2)
library(data.table)
library(ggbreak) 
library(ggpubr)
library(gridExtra)
source("/project/xinhe/shengqian/cTWAS_simulation/code/simulation_help_functions.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_basic_plots.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_ctwas_plots.R")

plot_Prior <- function(results_dir, runtag, simutags, thin, group_prior_var_structure, null_method, file_name, prior_true) {
  plots <- list()  # Store plots in a list
  plot_idx <- 1
  
  for (simutag in names(simutags)) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[simutag]], thin, group_prior_var_structure, null_method, file_name)
      
    df <- data.frame(null_method = rep(c("blood E", "blood S", "blood ST"), each = 10),
                       pos = c(rep(1, 10), rep(2, 10), rep(3, 10)),
                       prior = c(param_df_ctwas$`prior_Whole_Blood|expression`, param_df_ctwas$`prior_Whole_Blood|splicing`,
                               param_df_ctwas$`prior_Whole_Blood|stability`)) 
      
    df$pos <- jitter(df$pos, amount = 0.2)
    
    # Prepare hline data: start and end x for each group
    hline_df <- data.frame(
      pos = 1:length(prior_true[[simutag]]),
      yintercept = unlist(prior_true[[simutag]])
    )
      
    p <- ggplot(df, aes(x = pos, y = prior, group = null_method, color = null_method)) +
        geom_point() +
        geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept),
                 linetype = "dashed", inherit.aes = FALSE) +
        labs(x = "", y = "Prior", title = simutag) +
        scale_x_continuous(breaks = c(1, 2, 3), labels = c("blood E", "blood S", "blood ST")) +
        ylim(c(0,0.015)) +
        theme_minimal()+
        theme(legend.position = "none")
      
    plots[[plot_idx]] <- p  # Store plot in the list
    plot_idx <- plot_idx + 1
  }
  
  if (length(plots) > 1) {
    grid.arrange(grobs = plots, ncol = length(plots))  # Using gridExtra
  } else {
    print(plots[[1]])
  }
}

plot_enrichment <- function(results_dir, runtag, simutags, thin, group_prior_var_structure, null_method, file_name, enrichment_true) {
  plots <- list()  # Store plots in a list
  plot_idx <- 1
  
  for (simutag in names(simutags)) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[simutag]], thin, group_prior_var_structure, null_method, file_name)
      
    df <- data.frame(null_method = rep(c("blood E", "blood S", "blood ST"), each = 10),
                       pos = c(rep(1, 10), rep(2, 10), rep(3, 10)),
                       enrichment = c(param_df_ctwas$`enrichment_Whole_Blood|expression`, param_df_ctwas$`enrichment_Whole_Blood|splicing`,
                                      param_df_ctwas$`enrichment_Whole_Blood|stability`),
                       se = c(param_df_ctwas$`enrichment_se_Whole_Blood|expression`, param_df_ctwas$`enrichment_se_Whole_Blood|splicing`,
                              param_df_ctwas$`enrichment_se_Whole_Blood|stability`)) 
      
    df$pos <- jitter(df$pos, amount = 0.2)
    
    # Prepare hline data: start and end x for each group
    hline_df <- data.frame(
      pos = 1:length(enrichment_true[[simutag]]),
      yintercept = unlist(enrichment_true[[simutag]])
    )
      
    p <- ggplot(df, aes(x = pos, y = enrichment, group = null_method, color = null_method)) +
        geom_point() +
        geom_errorbar(aes(ymin = enrichment - 1.96 * se, ymax = enrichment + 1.96 * se), width = 0.01) +
        geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept),
                 linetype = "dashed", inherit.aes = FALSE) +
        labs(x = "", y = "log(Enrichment)", title = simutag) +
        scale_x_continuous(breaks = c(1, 2, 3), labels = c("blood E", "blood S", "blood ST")) +
        ylim(c(-5,5)) +
        theme_minimal()+
        theme(legend.position = "none")
      
    plots[[plot_idx]] <- p  # Store plot in the list
    plot_idx <- plot_idx + 1
  }
  
  if (length(plots) > 1) {
    grid.arrange(grobs = plots, ncol = length(plots))  # Using gridExtra
  } else {
    print(plots[[1]])
  }
}

plot_PVE <- function(results_dir, runtag, simutags, thin, group_prior_var_structure, null_method, file_name, PVE_true) {
  plots <- list()  # Store plots in a list
  plot_idx <- 1
  
  for (simutag in names(simutags)) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[simutag]], thin, group_prior_var_structure, null_method, file_name)
      
    df <- data.frame(null_method = rep(c("blood E", "blood S", "blood ST"), each = 10),
                       pos = c(rep(1, 10), rep(2, 10), rep(3, 10)),
                       pve = c(param_df_ctwas$`pve_Whole_Blood|expression`, param_df_ctwas$`pve_Whole_Blood|splicing`,
                               param_df_ctwas$`pve_Whole_Blood|stability`)) 
      
    df$pos <- jitter(df$pos, amount = 0.2)
    
    # Prepare hline data: start and end x for each group
    hline_df <- data.frame(
      pos = 1:length(PVE_true[[simutag]]),
      yintercept = unlist(PVE_true[[simutag]])
    )
      
    p <- ggplot(df, aes(x = pos, y = pve, group = null_method, color = null_method)) +
        geom_point() +
        geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept),
                 linetype = "dashed", inherit.aes = FALSE) +
        labs(x = "", y = "PVE", title = simutag) +
        scale_x_continuous(breaks = c(1, 2, 3), labels = c("blood E", "blood S", "blood ST")) +
        ylim(c(0,0.1)) +
        theme_minimal()+
        theme(legend.position = "none")
      
    plots[[plot_idx]] <- p  # Store plot in the list
    plot_idx <- plot_idx + 1
  }
  
  if (length(plots) > 1) {
    grid.arrange(grobs = plots, ncol = length(plots))  # Using gridExtra
  } else {
    print(plots[[1]])
  }
}

plot_PHE <- function(results_dir, runtag, simutags, thin, group_prior_var_structure, null_method, file_name, PHE_true) {
  plots <- list()  # Store plots in a list
  plot_idx <- 1
  
  for (simutag in names(simutags)) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[simutag]], thin, group_prior_var_structure, null_method, file_name)
      
    df <- data.frame(null_method = rep(c("blood E", "blood S", "blood ST"), each = 10),
                       pos = c(rep(1, 10), rep(2, 10), rep(3, 10)),
                       phe = c(param_df_ctwas$`prop_heritability_Whole_Blood|expression`, param_df_ctwas$`prop_heritability_Whole_Blood|splicing`,
                               param_df_ctwas$`prop_heritability_Whole_Blood|stability`)) 
      
    df$pos <- jitter(df$pos, amount = 0.2)
    
    # Prepare hline data: start and end x for each group
    hline_df <- data.frame(
      pos = 1:length(PHE_true[[simutag]]),
      yintercept = unlist(PHE_true[[simutag]])
    )
      
    p <- ggplot(df, aes(x = pos, y = phe, group = null_method, color = null_method)) +
        geom_point() +
        geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept),
                 linetype = "dashed", inherit.aes = FALSE) +
        labs(x = "", y = "PHE", title = simutag) +
        scale_x_continuous(breaks = c(1, 2, 3), labels = c("blood E", "blood S", "blood ST")) +
        ylim(c(0,0.15)) +
        theme_minimal()+
        theme(legend.position = "none")
      
    plots[[plot_idx]] <- p  # Store plot in the list
    plot_idx <- plot_idx + 1
  }
  
  if (length(plots) > 1) {
    grid.arrange(grobs = plots, ncol = length(plots))  # Using gridExtra
  } else {
    print(plots[[1]])
  }
}
```

```{r echo=FALSE}
plot_molecular_PIPs <- function(results_dir, runtag,  simutags, group_prior_var_structure, null_method, ...){
  phenofs <- paste0(results_dir, runtag, "_simu", simutags, "-pheno.Rd")
  susieIfs <- paste0(results_dir, runtag, "_simu",simutags, ".thin1.",group_prior_var_structure,".",null_method,".minp08.mingene0.estimated_parameter.finemap_regions_res.RDS")
  f1 <- caliPIP_plot(phenofs, susieIfs, ...) 
  return(f1)
}

plot_gene_PIPs <- function(results_dir, runtag,  simutags, group_prior_var_structure, null_method, mapping_table, ...){
  phenofs <- paste0(results_dir, runtag, "_simu", simutags, "-pheno.Rd")
  susieIfs <- paste0(results_dir, runtag, "_simu",simutags, ".thin1.",group_prior_var_structure,".",null_method,".minp08.mingene0.estimated_parameter.finemap_regions_res.RDS")
  f1 <- caliPIP_plot_multi_omics(phenofs, susieIfs, mapping_table, ...) 
  return(f1)
}
```

## Simulation Parameters
```{r eval=FALSE}
pve_gene <- c(0.02, 0.01, 0.003)
group_size <- c(8170,13273,3479)
pve_snp <- 0.3
sigma_theta <- 0.02
sigma_beta <- 0.02
gene_prior <- c(0.009175339,0.002823872,0.003232072)
snp_prior <- 0.0002248876
```


```{r echo=FALSE}
pve_gene <- c(0.02, 0.01, 0.003)
group_size <- c(8170,13273,3479)
pve_snp <- 0.3
sigma_theta <- 0.02
sigma_beta <- 0.02
gene_prior <- pve_gene/sigma_beta^2/(1-sum(pve_gene)-pve_snp)/group_size
#[1] 0.009175339 0.002823872 0.003232072
snp_prior <- pve_snp/sigma_beta^2/(1-sum(pve_gene)-pve_snp)/5000000
#[1] 0.0002248876


simutags <- list("group1"=paste(1, 1:10, sep = "-"))

prior_true <- list("group1" = gene_prior)
  
enrichment_true <- list("group1"= log(gene_prior/snp_prior,base = exp(1)))

pve_true <- list("group1"=pve_gene)

phe_true <- list("group1"=pve_gene/(sum(pve_gene)+pve_snp))
```

## shared_all, ctwas null weight

### Prior
```{r,echo=FALSE,fig.width= 4, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_three_omics/"
runtag = "one_tissues_three_omics"
plot_Prior(results_dir,runtag,simutags,1,"shared_all","ctwas",".niter_prefit10.minp08.mingene0.parameters.RDS",prior_true)
```

### Enrichment
```{r,echo=FALSE,fig.width= 4, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_three_omics/"
runtag = "one_tissues_three_omics"
plot_enrichment(results_dir,runtag,simutags,1,"shared_all","ctwas",".niter_prefit10.minp08.mingene0.parameters.RDS",enrichment_true)
```

## PVE
```{r,echo=FALSE,fig.width= 4, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_three_omics/"
runtag = "one_tissues_three_omics"
plot_PVE(results_dir,runtag,simutags,1,"shared_all","ctwas",".minp08.mingene0.parameters.RDS",pve_true)
```

## PHE
```{r,echo=FALSE,fig.width= 4, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_three_omics/"
runtag = "one_tissues_three_omics"
plot_PHE(results_dir,runtag,simutags,1,"shared_all","ctwas",".niter_prefit10.minp08.mingene0.parameters.RDS",phe_true)
```

### Molecular level PIP
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=4, fig.height=4}
simutags <- list("group1"=  paste(1, 1:10, sep = "-"))
molecular_PIPs <- list()
for(i in names(simutags)){
  print(i)
  f1 <- plot_molecular_PIPs(results_dir, runtag, simutags[[i]], "shared_all", "ctwas", main = i)
  molecular_PIPs[[i]] <- f1
}
do.call(grid.arrange, c(molecular_PIPs, ncol = 1))
```

### Gene level PIP
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=4, fig.height=4}
mapping_table1 <- readRDS("/project2/xinhe/shared_data/multigroup_ctwas/weights/mapping_files/PredictDB_E_S_M_mapping.RDS")
mapping_table2 <- readRDS("/project2/xinhe/shared_data/multigroup_ctwas/weights/mapping_files/Munro_mapping.RDS")
mapping_table <- rbind(mapping_table1,mapping_table2)
simutags <- list("group1"=  paste(1, 1:10, sep = "-"))
gene_PIPs <- list()
for(i in names(simutags)){
  print(i)
  f1 <- plot_gene_PIPs(results_dir, runtag, simutags[[i]], "shared_all", "ctwas", mapping_table, main = i)
  gene_PIPs[[i]] <- f1
}
do.call(grid.arrange, c(gene_PIPs, ncol = 1))
```