---
title: "simulation_one_tissue_enrichment"
output: html_document
date: '2024-4-28'
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(ctwas)
library(tidyr)
library(dplyr)
library(ggplot2)
library(data.table)
library(ggbreak) 
library(ggpubr)
library(gridExtra)
source("/project/xinhe/shengqian/cTWAS_simulation/code/simulation_help_functions.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_basic_plots.R")
source("/project/xinhe/shengqian/cTWAS_simulation/code/summarize_ctwas_plots.R")

plot_prior <- function(results_dir, runtag, simutags, group_prior_var_structures, null_methods, file_name, prior_true) {
  plot_df <- data.frame()
  
  for (i in 1:length(names(simutags))) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[names(simutags)[i]]], 1, group_prior_var_structures, null_methods, file_name)
    df <- data.frame(
      group = rep(names(simutags)[i], each = 10),
      pos = rep(i, 10),
      prior = c(param_df_ctwas$`prior_Whole_Blood|expression`),
      se = c(0,10)
    )
    
    df$pos <- jitter(df$pos, amount = 0.2)
    plot_df <- rbind(plot_df, df)
  }
  
  # Prepare hline data: start and end x for each group
  hline_df <- data.frame(
    group = names(prior_true),
    pos = 1:length(prior_true),
    yintercept = unlist(prior_true)
  )
  
  # Plot
  p <- ggplot(plot_df, aes(x = pos, y = prior, group = group, color = group)) +
    geom_point() +
    geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept, color = group),
                 linetype = "dashed", inherit.aes = FALSE) +
    labs(x = "", y = "Prior", title = "") +
    scale_x_continuous(breaks = 1:5, labels = names(simutags)) +
    ylim(c(0,0.4)) +
    theme_minimal() +
    theme(
      legend.position = "none",
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    )
  
  print(p)
}

plot_enrichment <- function(results_dir, runtag, simutags, group_prior_var_structures, null_methods, file_name, enrichment_true) {
  plot_df <- data.frame()
  
  for (i in 1:length(names(simutags))) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[names(simutags)[i]]], 1, group_prior_var_structures, null_methods, file_name)
    df <- data.frame(
      group = rep(names(simutags)[i], each = 10),
      pos = rep(i, 10),
      enrichment = c(param_df_ctwas$`enrichment_Whole_Blood|expression`),
      se = c(param_df_ctwas$`enrichment_se_Whole_Blood|expression`)
    )
    
    df$pos <- jitter(df$pos, amount = 0.2)
    plot_df <- rbind(plot_df, df)
  }
  
  # Prepare hline data: start and end x for each group
  hline_df <- data.frame(
    group = names(enrichment_true),
    pos = 1:length(enrichment_true),
    yintercept = unlist(enrichment_true)
  )
  
  # Plot
  p <- ggplot(plot_df, aes(x = pos, y = enrichment, group = group, color = group)) +
    geom_point() +
    geom_errorbar(aes(ymin = enrichment - 1.96 * se, ymax = enrichment + 1.96 * se), width = 0.01) +
    geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept, color = group),
                 linetype = "dashed", inherit.aes = FALSE) +
    labs(x = "", y = "log(Enrichment)", title = "") +
    scale_x_continuous(breaks = 1:5, labels = names(simutags)) +
    ylim(c(-5,5)) +
    theme_minimal() +
    theme(
      legend.position = "none",
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    )
  
  print(p)
}

plot_prop_PVE <- function(results_dir, runtag, simutags, group_prior_var_structures, null_methods, file_name, prop_pve_true) {
  plot_df <- data.frame()
  
  for (i in 1:length(names(simutags))) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[names(simutags)[i]]], 1, group_prior_var_structures, null_methods, file_name)
    df <- data.frame(
      group = rep(names(simutags)[i], each = 10),
      pos = rep(i, 10),
      prop_pve = c(param_df_ctwas$`prop_heritability_Whole_Blood|expression`),
      #gene_prior <- param_df_ctwas$`prior_Whole_Blood|expression`,
      #snp_prior <- param_df_ctwas$`prior_SNP`,
      #prop_pve = c((gene_prior/snp_prior)/((gene_prior/snp_prior)+500000/8170)),
      se = c(0,10)
    )
    
    df$pos <- jitter(df$pos, amount = 0.2)
    plot_df <- rbind(plot_df, df)
  }
  
  # Prepare hline data: start and end x for each group
  hline_df <- data.frame(
    group = names(prop_pve_true),
    pos = 1:length(prop_pve_true),
    yintercept = unlist(prop_pve_true)
  )
  
  # Plot
  p <- ggplot(plot_df, aes(x = pos, y = prop_pve, group = group, color = group)) +
    geom_point() +
    geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept, color = group),
                 linetype = "dashed", inherit.aes = FALSE) +
    labs(x = "", y = "Proportion of PVE", title = "") +
    scale_x_continuous(breaks = 1:5, labels = names(simutags)) +
    ylim(c(0,1)) +
    theme_minimal() +
    theme(
      legend.position = "none",
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    )
  
  print(p)
}

plot_PVE <- function(results_dir, runtag, simutags, group_prior_var_structures, null_methods, file_name, pve_true) {
  plot_df <- data.frame()
  
  for (i in 1:length(names(simutags))) {
    param_df_ctwas <- load_parameters(results_dir, runtag, simutags[[names(simutags)[i]]], 1, group_prior_var_structures, null_methods, file_name)
    df <- data.frame(
      group = rep(names(simutags)[i], each = 10),
      pos = rep(i, 10),
      pve = c(param_df_ctwas$`pve_Whole_Blood|expression`),
      se = c(0,10)
    )
    
    df$pos <- jitter(df$pos, amount = 0.2)
    plot_df <- rbind(plot_df, df)
  }
  
  # Prepare hline data: start and end x for each group
  hline_df <- data.frame(
    group = names(pve_true),
    pos = 1:length(pve_true),
    yintercept = unlist(pve_true)
  )
  
  # Plot
  p <- ggplot(plot_df, aes(x = pos, y = pve, group = group, color = group)) +
    geom_point() +
    geom_segment(data = hline_df,
                 aes(x = pos - 0.3, xend = pos + 0.3, 
                     y = yintercept, yend = yintercept, color = group),
                 linetype = "dashed", inherit.aes = FALSE) +
    labs(x = "", y = "PVE", title = "") +
    scale_x_continuous(breaks = 1:5, labels = names(simutags)) +
    ylim(c(0,0.4)) +
    theme_minimal() +
    theme(
      legend.position = "none",
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    )
  
  print(p)
}
```

## Simulation Parameters
```{r eval=FALSE}
pve_gene <-   c(0.005,    0.05,     0.1,       0.2,       0.4)
pi_gene =     c(0.0025,   0.025,    0.05,      0.1,       0.2)
size_gene =   c(8170,     8170,     8170,      8170,      8170)

pve_snp <-    c(0.3,      0.3,      0.3,       0.3,       0.3)
pi_snp =      c(0.0025,   0.0025,   0.0025,    0.0025,    0.0025)
size_snp =    c(500000,   500000,   500000,    500000,    500000)
```

```{r echo=FALSE}
simutags <- list("enrichment 1"=paste(1, 1:10, sep = "-"),
                 "enrichment 10"=paste(2, 1:10, sep = "-"),
                 "enrichment 20"=paste(3, 1:10, sep = "-"),
                 "enrichment 40"=paste(4, 1:10, sep = "-"),
                 "enrichment 80"=paste(5, 1:10, sep = "-"))

enrichment_true <- list("1"=0,
                        "2"=log(10,base=exp(1)),
                        "3"=log(20,base=exp(1)),
                        "4"=log(40,base=exp(1)),
                        "5"=log(80,base=exp(1)))

#pi <- c(0.0025,   0.025,    0.05,      0.1,       0.2)
#pve_gene <- c(0.005,      0.05,      0.1,       0.2,       0.4)
#pve_snp <- c(0.3,      0.3,      0.3,       0.3,       0.3)
#sigma_beta <- c(0.0155,   0.0155,   0.0155,    0.0155,    0.0155)
#gene_size <- 8170
#pve <- sigma_beta^2 * pi * gene_size

prior_true <- list("1"= 0.0025,
                 "2"= 0.025,
                 "3"= 0.05,
                 "4"= 0.1,
                 "5"= 0.2)

pve_true <- list("1"= 0.005,
                 "2"= 0.05,
                 "3"= 0.1,
                 "4"= 0.2,
                 "5"= 0.4)

prop_pve_true <- list("1"= 0.01639344,
                      "2"= 0.14285714,
                      "3"= 0.25000000,
                      "4"= 0.40000000,
                      "5"= 0.57142857)

#pve_data <- c()
#for(i in names(simutags)){
#  tmp_pve <- c()
#  for(j in simutags[[i]]){
#    pve <- get(load(paste0("/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_PVE/one_tissue_simu",j,"-pheno.Rd")))
#    pve <- pve$param$pve.gene.truth
#    tmp_pve <- c(tmp_pve,pve)
#  }
#  pve_data <- c(pve_data,mean(tmp_pve))
#}

#pve_data <- list("1"=pve_data[1],
#                 "2"=pve_data[2],
#                 "3"=pve_data[3],
#                 "4"=pve_data[4],
#                 "5"=pve_data[5])

#prop_data <- c()
#for(i in names(simutags)){
#  tmp_prop <- c()
#  for(j in simutags[[i]]){
#    prop <- get(load(paste0("/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_PVE/one_tissue_simu",j,"-pheno.Rd")))
#    gene_pve <- prop$param$pve.gene.truth
#    snp_pve <- prop$param$pve.snp.truth
#    tmp_prop <- c(tmp_prop,gene_pve/(gene_pve+snp_pve))
#  }
#  prop_data <- c(prop_data,mean(tmp_prop))
#}

#prop_data <- list("1"=prop_data[1],
#                 "2"=prop_data[2],
##                 "3"=prop_data[3],
#                 "4"=prop_data[4],
#                 "5"=prop_data[5])
```

## shared_all, ctwas null weight

### Prior
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_PVE/"
runtag = "one_tissue"
plot_prior(results_dir,runtag,simutags,"shared_all","ctwas",".Gtest.minp08.mingene0.parameters.RDS",prior_true)
```

### Enrichment
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_PVE/"
runtag = "one_tissue"
plot_enrichment(results_dir,runtag,simutags,"shared_all","ctwas",".Gtest.minp08.mingene0.parameters.RDS",enrichment_true)
```

### PVE
```{r echo=FALSE}
plot_PVE(results_dir,runtag,simutags,"shared_all","ctwas",".Gtest.minp08.mingene0.parameters.RDS",pve_true)
```

### Proportion of PVE
```{r echo=FALSE}
plot_prop_PVE(results_dir,runtag,simutags,"shared_all","ctwas",".Gtest.minp08.mingene0.parameters.RDS",prop_pve_true)
```

## shared_all, susie null weight

### Prior
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
results_dir <- "/project/xinhe/shengqian/cTWAS_simulation/simulation_one_tissue_expression_PVE/"
runtag = "one_tissue"
plot_prior(results_dir,runtag,simutags,"shared_all","susie",".Gtest.minp08.mingene0.parameters.RDS",prior_true)
```

### Enrichment
```{r,echo=FALSE,fig.width= 8, fig.height= 4}
plot_enrichment(results_dir,runtag,simutags,"shared_all","susie",".Gtest.minp08.mingene0.parameters.RDS",enrichment_true)
```

### PVE
```{r echo=FALSE}
plot_PVE(results_dir,runtag,simutags,"shared_all","susie",".Gtest.minp08.mingene0.parameters.RDS",pve_true)
```

### Proportion of PVE
```{r echo=FALSE}
plot_prop_PVE(results_dir,runtag,simutags,"shared_all","susie",".Gtest.minp08.mingene0.parameters.RDS",prop_pve_true)
```